version: "3"
services:
  node-app:
    build: .
    image: hahmadipoor/testapp3_node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image : mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hossein
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
volumes:
  mongo-db:
      

      